name: medicare_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  firebase_messaging: ^14.9.0
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.2.3
  flutter_timezone: ^4.1.1
  permission_handler: ^11.3.1
  timezone: ^0.9.4
  mailer: ^6.3.0
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1
  android_intent_plus: ^5.3.1
  flutter_tts: ^4.2.3
  shared_preferences: ^2.3.3
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.4.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
